### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by ijn115449** [SashiDo/content-moderation-image-api#2]
![err](https://user-images.githubusercontent.com/15447276/91906269-8238af00-ecda-11ea-8c46-35baa80f7d2a.JPG)
pls help me

**Comment by ijn115449** [comment]
[2020-09-01T21_05_29_748Z-debug.log](https://github.com/SashiDo/content-moderation-image-api/files/5158894/2020-09-01T21_05_29_748Z-debug.log)

**Comment by pivanov** [comment]
Hey,
It looks that there is an issue with the postinstall script.
Can you try to run `npm install --ignore-scripts` this will skip the `postinstall` script.
If everything is OK. Than you can run `npm run dev`.

P.S. Don't remove the `postinstall` script. You will need it when you deploy your app to SashiDo.

**Comment by ijn115449** [comment]
![err2](https://user-images.githubusercontent.com/15447276/92001285-15242880-ed71-11ea-8f46-d105c5729a67.JPG)
[2020-09-02T15_06_45_459Z-debug.log](https://github.com/SashiDo/content-moderation-image-api/files/5163138/2020-09-02T15_06_45_459Z-debug.log)

**Comment by pivanov** [comment]
Hmm ... it looks that some package have issues running on Windows.
Let's try to isolate the problem. Can you try:

1. run `npm run build`
2. run `npm run dev:cloud`
3. run `npm run dev:parse-server`

If all 3 steps work separately it means that "npm-run-all" has some issues on Windows.
Thanks for your help!

**Comment by ijn115449** [comment]
hey , i try npm install and npm run dev on WSL，it's work
so that is windows platform problem.
![work1](https://user-images.githubusercontent.com/15447276/92086089-485fc980-edfc-11ea-8eb7-8367905c08a4.JPG)

thank you
